config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
      resources :doses, only: [:new, :create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id, :ingredient_id, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

    def index
      @cocktails = Cocktail.all

    end

    def show
    end

    def new
      @cocktail = Cocktail.new
    end

    def destroy
      @cocktail.destroy

      # no need for app/views/cocktails/destroy.html.erb
      redirect_to cocktails_path
    end

    def create
      @cocktail = Cocktail.new(cocktail_params)
      @cocktail.save
    # Will raise ActiveModel::ForbiddenAttributesError
      redirect_to cocktail_path(@cocktail)
    end

    def edit
    end

    def update
      @cocktail.update(cocktail_params)

      redirect_to cocktail_path(@cocktail)
    end

    private

    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

    before_action :set_cocktail, only: [:create, :new, :show, :edit, :update, :destroy]


    def new
      @dose = Dose.new

    end

    def create
      @dose = Dose.new(dose_params)
      @dose.cocktail = @cocktail
      @dose.save!
    # Will raise ActiveModel::ForbiddenAttributesError
      redirect_to cocktail_path(@cocktail)
    end


    def index
      @doses = Dose.all
    end

    def show
    end

    def destroy
       @dose = Dose.find(params[:id])
      @dose.destroy

      # no need for app/views/doses/destroy.html.erb
      redirect_to cocktail_path(@cocktail)
    end

    def edit
    end

    def update
      @dose.update(dose_params)

      redirect_to dose_path(@dose)
    end

    private

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

    def index
      @ingredients = Ingredient.all
    end

    def show
    end

    def new
      @ingredient = Ingredient.new
    end

    def destroy
      @ingredient.destroy

      # no need for app/views/ingredients/destroy.html.erb
      redirect_to ingredients_path
    end

    def create
      @ingredient = Ingredient.new(ingredient_params)
      @ingredient.save
    # Will raise ActiveModel::ForbiddenAttributesError
      redirect_to ingredient_path(@ingredient)
    end

    def edit
    end

    def update
      @ingredient.update(ingredient_params)

      redirect_to ingredient_path(@ingredient)
    end

    private

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Create me' %>
<% end %>

app/views/cocktails/edit.html.erb
<%= render "form", cocktail: @cocktail %>

<br>
<%= link_to "Show all cocktails", cocktails_path %>

app/views/cocktails/new.html.erb
<%= render "form", cocktail: @cocktail %>
<br>
<%= link_to "Show all cocktails", cocktails_path %>

app/views/cocktails/show.html.erb
<h5><%= link_to "Cocktails", cocktails_path %></h5>
<br><br>
<h2><%= @cocktail.name %></h2>
<br>
<% @cocktail.doses.each do |dose| %>
<p><%= dose.ingredient.name %></p>
<p><%= dose.description %></p>
<%= link_to "Delete #{dose.ingredient.name}",
            cocktail_dose_path(@cocktail, dose),
            method: :delete,
            data: { confirm: "Quer deletar a dose?" } %>
<% end %>

<br><br>
<%= link_to "Delete #{@cocktail.name}",
            cocktail_path(@cocktail),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<h4><%= link_to "Edit", edit_cocktail_path %></h4>
<h4><%= link_to "Show all cocktails", cocktails_path %></h4>
<h4><%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail) %></h4>

app/views/doses/_form.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/edit.html.erb
<%= render "form", dose: @dose %>

<br>
<%= link_to "Show all doses", doses_path %>

app/views/doses/index.html.erb
<h1><%= 'Doses'%></h1>

<% @doses.each do |t|  %>
  <div class="flexbox">
    <li>
    <h5><%= link_to t.name, dose_path(t) %></h5>
  </li>
  </div>

<% end %>

  <h4><%= link_to "+ Add new dose", new_dose_path %><h4>

app/views/doses/new.html.erb
<%= render "form", cocktail: @cocktail, dose: @dose %>

<br>
<%= link_to "Show all doses", cocktail_doses_path %>

app/views/doses/show.html.erb
<h5><%= link_to "Amerinimous", doses_path %></h5>
<br><br>
<h2><%= @dose.name %></h2>
<br>
<br><br>
<%= link_to "Delete #{@dose.name}",
            dose_path(@dose),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<h4><%= link_to "Edit", edit_dose_path %></h4>
<h4><%= link_to "Show all doses", doses_path %></h4>
<h4><%= link_to "Add a new dose", new_cocktail_dose_path(@dose) %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="pcHFEYGAXeZ4Ul59qI1WfSffgbM52Wx6UVowv7N3ICZmktN4GI2Db+p6d4iDZ13bntvQZHUA0PuWurVNYT3sSg==" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel="stylesheet" media="all" href="/assets/application-6502403468dfbc20a08319e14cf02150d3c5cadebcd825473006e83ddf10c24e.css" data-turbolinks-track="reload" />
    <script src="/assets/application-dcfb333542166c7e176ac13945f5c27350627b932d212a870a5a112daf6d4db9.js" data-turbolinks-track="reload"></script>


    <title>Mister Cocktail do Bonza</title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>